const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.BBCMicroBit,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.BBCMicroBit.Acts.RequestDevice,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.BBCMicroBit.Exps.AccelerometerSmoothedX,
		C3.Plugins.BBCMicroBit.Exps.AccelerometerSmoothedY,
		C3.Plugins.BBCMicroBit.Cnds.OnButtonPressed,
		C3.Plugins.BBCMicroBit.Cnds.IsDeviceConnected,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetAcceleration
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{Platform: 0},
	{player: 0},
	{Solid: 0},
	{platform: 0},
	{coin: 0},
	{obstacle1: 0},
	{Rotate: 0},
	{obstacle2: 0},
	{Particles: 0},
	{Score: 0},
	{Score_Number: 0},
	{enemy_barrier: 0},
	{Move: 0},
	{enemy: 0},
	{Keyboard: 0},
	{BBCMicrobit: 0},
	{Connect: 0},
	{disconnect: 0},
	{MB_Y: 0},
	{MB_X: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	obstacle1: class extends self.ISpriteInstance {},
	obstacle2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Score: class extends self.ITextInstance {},
	Score_Number: class extends self.ITextInstance {},
	enemy_barrier: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BBCMicrobit: class extends self.IInstance {},
	Connect: class extends self.IButtonInstance {},
	disconnect: class extends self.IButtonInstance {}
}